<?php
function famelab_glu_init(){

}

function famelab_glu_feedapi_mapper($op, $node, $field_name, $feed_element = array(), $sub_field = ''){

     switch ($op){
         case 'describe':
             return t('Maps a URL to an EmField');
             break;
         case 'list':
             return true;
             break;
         case 'map';
            if (!is_array($feed_element)) {
                $field = $node->$field_name;
                $field[0]['value'] = $feed_element;
                $node->$field_name = $field;
            }
            return $node;
            break;
     }
}


function famelab_glu_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL){
    switch ($op){
        case 'validate':
            
            if ($node->type == 'video'){
                $body = $node->body;
                $teaser = $node->teaser;

                $exp_body = explode("\n", $body);
                
                foreach($exp_body as $key=>$row){
                    $tmp = trim($row);
                    if (!empty($tmp) && $tmp != '<br/>'){
                        $values[] = trim($row);
                    }
                }

                $url = str_replace('<a href="', '', $values[0]);
                $url = str_replace('"></a>', '', $url);

                $embed_code = '<iframe title="YouTube video player" class="youtube-player" type="text/html" width="853" height="510" src="http://www.youtube.com/embed/'.$id.'?rel=0" frameborder="0"></iframe>';
   
                $node->field_embedded_video[0]['embed'] = $url;
                $node->body = '';
                $node->teaser = '';
            }
        break;
    }
}