<?php
global $api_key;
$api_key = 'ABQIAAAAuJmfCEX7NZHtiuXRtYUPCxScFrxffNo77mYOeXiz0SNXAsCCXhTFttZePHdU0aPDnYzjS3vz6IzBEw';

function famelab_map_menu(){
    $items = array();

    $items['international'] = array(
        'title' => 'Participating Countries',
        'page callback' => 'famelab_map_map',
        'access arguments' => array('access content'),
        'menu_name' => 'primary-links',
        'type' => MENU_NORMAL_ITEM,
    );

    return $items;
}

function famelab_map_init(){
 
}

function famelab_map_map(){
    drupal_set_html_head('<script src="http://maps.google.com/maps/api/js?sensor=false"" type="text/javascript"></script>');
    drupal_add_js(drupal_get_path('module', 'famelab_map') . '/jquery.gmap3.js', 'module', 'header');




    drupal_add_js(famelab_map_js(), 'inline', 'header');



    return '<div id="map_canvas" style="width:100%; height:500px"></div>';
}

function famelab_map_get_data(){
    $view = views_get_view('Countries');
    $display_id = 'default';
    $view->set_display($display_id);
    $view->set_items_per_page(0);
    $view->render();

    return ($view->result);
}

function famelab_map_js(){
    ob_start();
    ?>
    function createInfo(title, content) {

        return '<div id="popup"><h2 class="popup-title">' + title + '</h2><div id="popup-body">' + content + '</div></div>';
    }
    
    $(document).ready(function () {
        // create the map
        var map = $("#map_canvas").gmap3(
        {
            lat: 22.602,
            lng: 13.2683,
            zoom: 2
        });

    <?php
    $js = ob_get_contents();
    ob_end_clean();

    $data = famelab_map_get_data();
    foreach ($data as $node){
        $node->node_revisions_body = json_encode(check_markup($node->node_revisions_body));

      
        $js .= 'map.addMarkerByLatLng(' . $node->node_data_field_icon_colour_field_lat_value . ', ' . $node->node_data_field_icon_colour_field_lon_value . ', "'.$node->node_title.'", createInfo("'.$node->node_title.'", '.$node->node_revisions_body.'));';

    }

    $js .= '});';

    return $js;

}
