<?php
global $api_key;
$api_key = 'ABQIAAAAuJmfCEX7NZHtiuXRtYUPCxScFrxffNo77mYOeXiz0SNXAsCCXhTFttZePHdU0aPDnYzjS3vz6IzBEw';

function famelab_map_menu(){
    $items = array();

    $items['international'] = array(
        'title' => 'Participating Countries',
        'page callback' => 'famelab_map_map',
        'access arguments' => array('access content'),
        'menu_name' => 'primary-links',
        'type' => MENU_NORMAL_ITEM,
    );

    return $items;
}

function famelab_map_init(){
 
}

function famelab_map_map(){
    #Node 427 contains the map text
    $content = explode('##MAP##',node_load(427)->body);

    return $content[0] . '<iframe width="700" height="400" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="http://maps.google.com/maps/ms?ie=UTF8&amp;hl=en&amp;oe=UTF8&amp;msa=0&amp;msid=210276933778263433551.0004a96cfab363cca4f5b&amp;ll=16.772573,18.632812&amp;spn=84.986616,191.425781&amp;t=h&amp;output=embed"></iframe><br /><center><small>View <a href="http://maps.google.com/maps/ms?ie=UTF8&amp;hl=en&amp;oe=UTF8&amp;msa=0&amp;msid=210276933778263433551.0004a96cfab363cca4f5b&amp;ll=16.772573,18.632812&amp;spn=84.986616,191.425781&amp;t=h&amp;source=embed" style="color:#0000FF;text-align:left">FameLab International</a> in a larger map</small></center><br /><br />'. $content[1];
}

function famelab_map_get_data(){
    $view = views_get_view('Countries');
    $display_id = 'default';
    $view->set_display($display_id);
    $view->set_items_per_page(0);
    $view->render();

    return ($view->result);
}

function famelab_map_js(){
    ob_start();
    ?>
    function createInfo(title, content) {

        return '<div id="popup"><h2 class="popup-title">' + title + '</h2><div id="popup-body">' + content + '</div></div>';
    }
    
    $(document).ready(function () {
        // create the map
        var map = $("#map_canvas").gmap3(
        {
            lat: 22.602,
            lng: 13.2683,
            zoom: 2
        });

    <?php
    $js = ob_get_contents();
    ob_end_clean();

    $data = famelab_map_get_data();
    foreach ($data as $node){
        $node->node_revisions_body = json_encode(check_markup($node->node_revisions_body));

      
        $js .= 'map.addMarkerByLatLng(' . $node->node_data_field_icon_colour_field_lat_value . ', ' . $node->node_data_field_icon_colour_field_lon_value . ', "'.$node->node_title.'", createInfo("'.$node->node_title.'", '.$node->node_revisions_body.'));';

    }

    $js .= '});';

    return $js;

}
