<?php

function famelab_alumni_perm() {
  return array('view alumni content');
}

function famelab_alumni_init(){

}

function famelab_alumni_menu(){

    $items = array();

    $items['alumni/your_account'] = array(
        'title' => 'Your Account',
        'page callback' => 'famelab_alumni_your_account',
        'access arguments' => array('view alumni content'),
        'type' => MENU_SUGGESTED_ITEM,
        'menu_name' => 'primary-links'
        );

    return $items;

}
//Redirect Users to the their user page
function famelab_alumni_your_account(){
    $user = $GLOBALS['user'];
    $uid = $user->uid;
    if ($uid == 1){$uid = 9;}
    $path = drupal_lookup_path('alias', 'user/' . $uid);
    if ($path){
        drupal_goto($path);
    }else{
        drupal_goto('user/' . $uid);
    }
}

function famelab_alumni_form_alter(&$form, &$form_state, $form_id){

}